{% set name = "phasefieldx" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CastillonMiguel/phasefieldx/archive/v{{ version }}.tar.gz
  sha256: e5e2326c12127f1eee5fbf1dcbdc2d32e81ae159f2651531e8cd855d33f73728

build:
  number: 0
  noarch: python

  # openmpi oversubscribe env
  script_env:
    - OMPI_ALLOW_RUN_AS_ROOT=1
    - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    - OMPI_MCA_rmaps_base_oversubscribe=1
    - OMPI_MCA_plm=isolated
    - OMPI_MCA_btl=vader,self
    - OMPI_MCA_btl_vader_single_copy_mechanism=none
    - MPIEXEC_TIMEOUT=400

  script: python -m pip install . -vv

requirements:
  host:
    - python >=3.12
    - hatchling
    - pip
  run:
    - python >=3.12
    - fenics-dolfinx ==0.9.0
    - gmsh ==4.13.1
    - numpy ==2.1.1
    - pandas ==2.2.3
    - pyvista ==0.44.1

about:
  home: https://github.com/CastillonMiguel/phasefieldx
  summary: 'PhaseFieldX: An Open-Source Framework for Advanced Phase-Field Simulations'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://phasefieldx.readthedocs.io
  dev_url: https://github.com/CastillonMiguel/phasefieldx

extra:
  recipe-maintainers:
    - CastillonMiguel
