{% set name = "phasefieldx" %}
{% set version = "0.3.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5645d7286d5f24352d6db3b3336d77a43f6fca8e1491e160163a93c55aafc38c

build:
  number: 0
  noarch: python

  script: python -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - fenics-dolfinx ==0.10.0
    - gmsh
    - mpi4py
    - numpy
    - pandas
    - pytest
    - pyvista
    - scifem

test:
  imports:
    - phasefieldx
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/CastillonMiguel/phasefieldx
  summary: 'PhaseFieldX: An Open-Source Framework for Advanced Phase-Field Simulations'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://phasefieldx.readthedocs.io
  dev_url: https://github.com/CastillonMiguel/phasefieldx

extra:
  recipe-maintainers:
    - CastillonMiguel
